/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling.game;

import org.junit.Test;
import static org.junit.Assert.*;

public class BowlingGameTest {
    @Test public void testHasScoreMethod() {
        BowlingGame game = new BowlingGame();

        assertEquals(0, game.score());
    }
}
