/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fizzbuzz;

import org.junit.Test;
import static org.junit.Assert.*;

public class FizzBuzzCalculatorTest {
    @Test public void whenNumberIs_1_ThenReturns_1() {
        FizzBuzzCalculator calculator = new FizzBuzzCalculator();

        String result = calculator.calculate(1);

        assertEquals("1", result);
    }
}
