/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling.game;

public class BowlingGame {
    public void roll() {
    }

    public int score() {
        return 0;
    }
}
